service_proxy/config/routes.rb
ServiceProxy::Application.routes.draw do
  resources :sesiones

  resources :empresas

  resources :usuarios

end

service_proxy/app/models/empresa.rb
class Empresa < ActiveResource::Base

  #attr_accessor :nombre
  self.site = "http://192.168.1.8:3000"
end

service_proxy/app/models/sesion.rb
class Sesion < ActiveResource::Base
  self.site = "http://localhost:3001"
  self.primary_key = :_id
end

service_proxy/app/models/usuario.rb
class Usuario < ActiveResource::Base

  self.site = "http://localhost:3000"

end

service_proxy/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

service_proxy/app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  before_action :set_empresa, only: [:show, :edit, :update, :destroy]

  # GET /empresas
  # GET /empresas.json
  def index
    @empresas = Empresa.all
  end

  # GET /empresas/1
  # GET /empresas/1.json
  def show
  end

  # GET /empresas/new
  def new
    @empresa = Empresa.build
  end

  # GET /empresas/1/edit
  def edit
  end

  # POST /empresas
  # POST /empresas.json
  def create
    @empresa = Empresa.new(empresa: empresa_params)

    respond_to do |format|
      if @empresa.save
        format.html { redirect_to @empresa, notice: 'Empresa was successfully created.' }
        format.json { render action: 'show', status: :created, location: @empresa }
      else
        format.html { render action: 'new' }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empresas/1
  # PATCH/PUT /empresas/1.json
  def update
    respond_to do |format|
      if @empresa.update_attributes(empresa_params)
        format.html { redirect_to @empresa, notice: 'Empresa was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /empresas/1
  # DELETE /empresas/1.json
  def destroy
    @empresa.destroy
    respond_to do |format|
      format.html { redirect_to empresas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empresa
      @empresa = Empresa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empresa_params
      params[:empresa]
    end
end

service_proxy/app/controllers/sesiones_controller.rb
class SesionesController < ApplicationController
  before_action :set_sesion, only: [:show, :edit, :update, :destroy]

  # GET /sesiones
  # GET /sesiones.json
  def index
    @sesiones = Sesion.all
  end

  # GET /sesiones/1
  # GET /sesiones/1.json
  def show
  end

  # GET /sesiones/new
  def new
    @sesion = Sesion.new
  end

  # GET /sesiones/1/edit
  def edit
  end

  # POST /sesiones
  # POST /sesiones.json
  def create
    @sesion = Sesion.new(sesion_params)

    respond_to do |format|
      if @sesion.save
        format.html { redirect_to @sesion, notice: 'Sesion was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sesion }
      else
        format.html { render action: 'new' }
        format.json { render json: @sesion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sesiones/1
  # PATCH/PUT /sesiones/1.json
  def update
    respond_to do |format|
      if @sesion.update(sesion_params)
        format.html { redirect_to @sesion, notice: 'Sesion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sesion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sesiones/1
  # DELETE /sesiones/1.json
  def destroy
    @sesion.destroy
    respond_to do |format|
      format.html { redirect_to sesiones_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sesion
      @sesion = Sesion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sesion_params
      params.require(:sesion).permit(:token)
    end
end

service_proxy/app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.build

  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render action: 'show', status: :created, location: @usuario }
      else
        format.html { render action: 'new' }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update_attributes(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params[:usuario]
    end
end

service_proxy/app/helpers/application_helper.rb
module ApplicationHelper
end

service_proxy/app/helpers/empresas_helper.rb
module EmpresasHelper
end

service_proxy/app/helpers/sesiones_helper.rb
module SesionesHelper
end

service_proxy/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

service_proxy/app/views/empresas/_form.html.erb
<%= form_for(@empresa) do |f| %>
  <% if @empresa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@empresa.errors.count, "error") %> prohibited this empresa from being saved:</h2>

      <ul>
      <% @empresa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

service_proxy/app/views/empresas/edit.html.erb
<h1>Editing empresa</h1>

<%= render 'form' %>

<%= link_to 'Show', @empresa %> |
<%= link_to 'Back', empresas_path %>

service_proxy/app/views/empresas/index.html.erb
<h1>Listing empresas</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @empresas.each do |empresa| %>
      <tr>
        <td><%= empresa.nombre  %></td>
        <td><%= link_to 'Show', empresa %></td>
        <td><%= link_to 'Edit', edit_empresa_path(empresa) %></td>
        <td><%= link_to 'Destroy', empresa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Empresa', new_empresa_path %>

service_proxy/app/views/empresas/new.html.erb
<h1>New empresa</h1>

<%= render 'form' %>

<%= link_to 'Back', empresas_path %>

service_proxy/app/views/empresas/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_empresa_path(@empresa) %> |
<%= link_to 'Back', empresas_path %>

service_proxy/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ServiceProxy</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

service_proxy/app/views/sesiones/_form.html.erb
<%= form_for(@sesion) do |f| %>
  <% if @sesion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sesion.errors.count, "error") %> prohibited this sesion from being saved:</h2>

      <ul>
      <% @sesion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :token %><br>
    <%= f.text_field :token %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

service_proxy/app/views/sesiones/edit.html.erb
<h1>Editing sesion</h1>

<%= render 'form' %>

<%= link_to 'Show', @sesion %> |
<%= link_to 'Back', sesiones_path %>

service_proxy/app/views/sesiones/index.html.erb
<h1>Listing sesiones</h1>

<table>
  <thead>
    <tr>
      <th>Token</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sesiones.each do |sesion| %>
      <tr>
        <td><%= sesion.token %></td>
        <td><%= link_to 'Show', sesion %></td>
        <td><%= link_to 'Edit', edit_sesion_path(sesion) %></td>
        <td><%= link_to 'Destroy', sesion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sesion', new_sesion_path %>

service_proxy/app/views/sesiones/new.html.erb
<h1>New sesion</h1>

<%= render 'form' %>

<%= link_to 'Back', sesiones_path %>

service_proxy/app/views/sesiones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Token:</strong>
  <%= @sesion.token %>
</p>

<%= link_to 'Edit', edit_sesion_path(@sesion) %> |
<%= link_to 'Back', sesiones_path %>

service_proxy/app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

service_proxy/app/views/usuarios/edit.html.erb
<h1>Editing usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

service_proxy/app/views/usuarios/index.html.erb
<h1>Listing usuarios</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nombre  %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

service_proxy/app/views/usuarios/new.html.erb
<h1>New usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

service_proxy/app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>